# Configuration Settings for NEO-M8U device

ublox_gps_node:
  ros__parameters:
    debug: 1                    # Range 0-4 (0 means no debug statements will print)

    save:
      mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver
                                # Manager, Antenna, and Logging Configuration
      device: 4                 # Save to EEPROM

    device: /dev/ttyACM0
    frame_id: m8u
    rate: 4                     # in Hz
    nav_rate: 4                 # [# of measurement cycles], recommended 1 Hz, may
                                # be either 5 Hz (Dual constellation) or
                                # 8 Hz (GPS only)
    dynamic_model: airborne2    # Airborne < 2G, 2D fix not supported (3D only),
                                # Max Alt: 50km
                                # Max Horizontal Velocity: 250 m/s,
                                # Max Vertical Velocity: 100 m/s
    fix_mode: 3
    enable_ppp: true
    dr_limit: 1

    uart1:
      baudrate: 115200           # NEO-M8U specific
      in: 16                     # RTCM 3
      out: 16                    # No UART out for rover

    gnss:
      glonass: true              # Supported by NEO-M8U
      beidou: false              # Supported by NEO-M8U
      qzss: false                # Supported by NEO-M8U

    dgnss_mode: 3                # Fixed mode

    inf:
      all: true                  # Whether to display all INF messages in console

    # Enable u-blox message publishers
    publish:
      all: true
      esf: true
      aid:
        hui: false
      nav:
        posecef: false
